#Programa que imprima materias y credicos segun el semestre
print("Imprimir materias y creditos segun el numero del semestre")
print("")
print("Para ver las materias que se estan cursando o cursadas y sus creditos")
print("por favor ingrese el numero que se muestra segun el semestre")
print("")

semestre0=True

while semestre0>0 or semestre0<=10:
	print("1 primer semestre")
	print("2 segundo semestre")
	print("3 tercer semestre")
	print("4 cuarto semestre")
	print("5 quinto semestre")
	print("6 sexto semestre")
	print("7 septimo semestre")
	print("8 octavo semestre")
	print("9 noveno semestre")
	print("10 para Finalizar")
	print(" ")

	print("Ingrese numero del semestre")
	semestre0=float(input("Ingreselo aqui "))
	
	if semestre0==1:
		print(" ")
		print("--Las materias cursadas son--")
		print("")
		print(" 1.-Calculo direferencial")
		print(" Con 5 creditos")
		print("2.-Fundamentos de programacion")
		print(" Con 5 creditos")
		print("3.-Matemáticas discretas 1")
		print(" Con 5 creditos")
		print("4.-Introduccion a las TICS")
		print(" Con 3 creditos")
		print("5.-Taller de ética")
		print(" Con 4 creditos")
		print("6.-Fundamentos de investigacion")
		print(" Con 4 creditos")
		print(" ")

	elif semestre0==2:
		print(" ")
		print("--Las materias cursadas son--")
		print(" ")
		print("1.-Calculo integral")
		print(" Con 5 creditos")
		print("2.-Programación orientada a objetos")
		print(" Con 5 creditos")
		print("3.-Matematicas discretas 2")
		print(" Con 5 creditos")
		print("4.-Probabilidad y estadística")
		print(" Con 5 creditos")
		print("5.-Contabilidad y costos")
		print(" Con 5 creditos")
		print(" ")

	elif semestre0==3:
		print(" ")
		print("--Las materias cursadas son--")
		print(" ")
		print("1.-Matematicás aplicadas a comunicaciones")
		print(" Con 4 creditos")
		print("2.-Estructura y organización de datos")
		print(" Con 5 creditos")
		print("3.-Administración general")
		print(" Con 4 creditos")
		print("4.-Fundamentos de base de datos")
		print(" Con 5 creditos")
		print("5.-Electricidad y magnetismo")
		print(" Con 4 creditos")
		print("6.-Alebra lineal")
		print(" Con 5 creditos")
		print(" ")

	elif semestre0==4:
		print(" ")
		print("--Las materias cursadas son--")
		print(" ")
		print("1.-Análisis de señales y sistemas")
		print(" Con 5 creditos")
		print("2.-Programación 2")
		print(" Con 5 creditos")
		print("3.-Matemáticas para la toma de decisiones")
		print(" Con 5 creditos")
		print("Taller de base de datos")
		print(" Con 5 creditos")
		print("Circuitos eléctricos y electrónicos")
		print(" Con 5 creditos")
		print("Ingeniería de software")
		print(" Con 4 creditos")
		print(" ")

	elif semestre0==5:
		print(" ")
		print("--Las materias cursadas son--")
		print(" ")
		print("1.-Fundamentos de redes")
		print(" Con 5 creditos")
		print("2.-Telecomunicaciones")
		print(" Con 5 creditos")
		print("3.-Administración de proyectos")
		print(" Con 5 creditos")
		print("Base de datos distribuidas")
		print(" Con 5 creditos")
		print("Arquitectura de computadoras")
		print(" Con 4 creditos")
		print("Taller de ingeniería de software")
		print(" Con 4 creditos")
		print(" ")

	elif semestre0==6:
		print(" ")
		print("--Las materias cursadas son--")
		print(" ")
		print("1.-Redes de computadoras")
		print(" Con 5 creditos")
		print("2.-Programación web")
		print(" Con 5 creditos")
		print("3.-Desarrollo de emprendedores")
		print(" Con 5 creditos")
		print("4.-Taller de investigacion 1")
		print(" Con 4 creditos")
		print("5.-Sistemas operativos 1")
		print(" Con 4 creditos")
		print("6.-Tecnologías inalambricas")
		print(" Con 4 creditos")
		print(" ")

	elif semestre0==7:
		print(" ")
		print("--Las materias cursadas son--")
		print(" ")
		print("1.-Redes emergentes")
		print(" Con 5 creditos")
		print("2.-Desarrollo de aplicaciones para Dispositivos Moviles")
		print(" Con 5 creditos")
		print("3.-Desarrollo sustentable")
		print(" Con 5 creditos")
		print("4.-Taller de investigacion 2")
		print(" Con 4 creditos")
		print("5.-Sistemas operativos 2")
		print(" Con 5 creditos")
		print("6.-Negocioa electrónicos 1")
		print(" Con 4 creditos")
		print(" ")

	elif semestre0==8:
		print(" ")
		print("--Las materias cursadas son--")
		print("")
		print("1.-Administración y seguridad de redes")
		print(" Con 5 creditos")
		print("2.-Auditoría en tecnologías de la informacion")
		print(" Con 4 creditos")
		print("3.-Interacción humano camputadora")
		print(" Con 4 creditos")
		print("4.-Ingeniería del conocimiento")
		print(" Con 4 creditos")
		print("5.-Negocios electrónicos 2")
		print(" Con 4 creditos")
		print(" ")

	elif semestre0==9:
		print(" ")
		print("--Las materias cursadas son--")
		print(" ")
		print("1.-Especialidad")
		print(" Con 25 creditos")
		print("2.-Residencias profesionales")
		print(" Con 10 creditos")
		print("3.-Servicio social")
		print(" Con 10 creditos")
		print("4.-Actividades complementarias")
		print(" Con 5 creditos")
		print(" ")

	elif semestre0==10:
		print(" ")
		print("El programa a  Finalizado")
		print(" ")
		break;

print("**Gracias**")