print("*Datos del alumno")
print("Alejandro Herrera Ramos")
print("Ejido Fresnillo, Rincon de Romos, AGS.")
print("19/04/2002")
print("Azul y negro")
print("Pez koi")
print("*Preguntas")
print("¿Que es la programación?.")
print("Es un proceso de creacion de programas en la informatica; dando a conocer un codigo a una computadora para que haga lo que queremos que haga.")
print("¿Por qué es importante la programacion?.")
print("Por el simple echo del futuro, dondo a entender que es uno de los factores mas importantes ya que con ello lleva el avance de la tecnologia que es un factor importante en nuestra vida actual y el futuro.")
print("Explique con sus palabras ¿Que es herencia?")
print("Se puede decir que es una forma en la que una clase puede heredar metodos y atributos de otra, de las cuales estan ordenadas jerárquicamente.")
print("Explique con sus palabras ¿Que es poliformismo?")
print("Es la accion de envias un mismo mensaje a distintos objetos de tipos distintos.")
print("Explique con sus palabras ¿Que es abstracción?")
print("Es la forma de seleccionar datos mas relevantes de u objeto, dando en si una simplificación.")
print("Explique con sus palabras ¿Que es encapsulacion?")
print("Es cuando elegimos que propiedad de datos queremos que se tenga acceso a ellos o no.")